# Generated by Django 4.1.5 on 2023-01-25 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('abstractcomponent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='component.abstractcomponent')),
                ('type_tag', models.IntegerField(choices=[(0, 'Part'), (1, 'Assembly')])),
                ('part_only_data', models.TextField()),
                ('assembly_only_data', models.TextField()),
            ],
            bases=('component.abstractcomponent',),
        ),
        migrations.CreateModel(
            name='ComponentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('from_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_relation', to='component.component')),
                ('to_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_relation', to='component.component')),
            ],
            options={
                'unique_together': {('from_component', 'to_component')},
            },
        ),
        migrations.AddField(
            model_name='component',
            name='sub_components',
            field=models.ManyToManyField(blank=True, related_name='super_components', through='component.ComponentRelation', to='component.component'),
        ),
    ]
